baseurl = "https://vic3lord.github.io/"
languageCode = "en-us"
Title = "Or Elimelech"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright notice"
publishDir = "docs"
theme = "hugo_theme_pickles"

# Google Analytics API key.
# googleAnalytics = "Your Google Analytics tracking id"

[params]
  paginate = 10
  custom_css = ["/css/custom.css"]
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "orelimelech_"
  github = "vic3lord"
  bio = "SRE at StackPulse."
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Short subtitle"
  # Logo image. This is displayed ogp image.
  # logo = "/path/to/logo"
  # favicon = "/path/to/favicon"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
